<?php

namespace Database\Seeders;

use App\Models\CarServiceType;
use Illuminate\Database\Seeder;

class CarServiceTypeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //CarServiceType::truncate();
        $types= [
            'Standard Car Service- Petrol',
            'Standard Car Service- Diesel',
            'Car Bodywork (Denting-Painting)',
            'Car AC Service',
            'Car Doorstep Check-up & Minor Repairs',
            'Used Car Inspection',
            'Car Windshield Replacement',
            'General Car Inspection',
            'Express Car Wash',
            'Steam Car Wash',
            'Professional Car Wash',
            'Car Underbody Anti-rust Treatment',           
            'General Maintenance',
            'Spare Tire Installation',
            'Rotate Tires',
            'AC Low Pressure Hose Replacement',
            'Brake Hose Replacement',
            'Radiator Hose Replacement',
            'Exhaust Gas Recirculation (EGR) Tube Replacement',
            'Power Steering Pressure Hose Replacement',
            'Air Injection Hose Replacement',
            'Heater Bypass Tube Replacement',
            'Power Steering Return Hose Replacement',
            'Air Intake Hose Replacement',
            'Breather Hose Replacement',
            'Bypass Hose Replacement',
            'AC Refrigerant Suction Hose Replacement',
            'AC Refrigerant Discharge Hose Replacement',
            'AC Refrigerant Liquid Hose Replacement',
            'AC Suction Line Hose Assembly Replacement',
            'Air Filter Replacement',
            'Cabin Air Filter Replacement',
            'Fuel Filter Replacement',
            'AC Air Filter Replacement',
            'Clutch Fluid Replacement',
            'Transfer Case Fluid Replacement',
            'Brake System Flush',
            'Change Oil and Filter',
            'Cooling System Flush',
            'Radiator Flush',
            'Transmission Fluid Service',
            'Power Steering Fluid Service',
            'Serpentine/Drive Belt Replacement',
            'Timing Belt Replacement',
            'Drive Belt Tensioner Replacement',
            'Alternator Belt Replacement',
            'Power Steering Belt Replacement',
            'AC Belt Replacement',
            'Supercharger Belt Replacement',
            'AC Recharge',
            'Bleed Brakes',
            'Brake System Flush',
            'Change Oil and Filter',
            'Cooling System Flush',
            'Radiator Flush',
            'Spare Tire Installation',
            'Rotate Tires',
            'Transmission Fluid Service',
            'Tune-up',
            'Lubricate U-Joints',
            'Lubricate Ball Joints',
            'Lubricate Suspension',
            'Clean and Repack Wheel Bearing',
            'Lubricate Doors',
            'Lubricate Hood Hinge',
            'Lubricate Trunk',
            'Service Battery/cables',
            'Reset Indicator Lights',
            'Valve Clearance Adjustment',
            'Lubricate Driveshaft',
            'Lubricate Steering and Suspension',
            'Adjust Drum Brakes',
            'Adjust Drive Belts',
            'Adjust Clutch',
            'Adjust Ignition Timing',
            'Adjust Parking Brake Cable',
            'Adjust Throttle Valve Cable',
            'Clean Throttle Body',
            'Clean Evaporator Drain Tube',
            'Tighten Wheel Lug Nuts',
            'Pressure Test Radiator Cap',
            'Power Steering Fluid Service',
            'Trunk Latch Adjustment',
            'Timing Cover Gasket',
            'Heater Blower Motor Replacement',
            'Clunking noise when I drive over bumps (Inspection)',
            'Heater Blower Motor Resistor Replacement',
            'Banging noises when driving over the bumps (Inspection)',
        ];
       
        foreach ($types as $type) {
            CarServiceType::create([
                'major_service_type_id' => 1,
                'serviceType' => $type]);
        }
        
        $tp2= [
            'Change Oil and Filter',
            'Brake Pads Replacement',
            'Check Engine Light is on (Inspection)',
            'Car is not starting (Inspection)',
            'Pre-purchase Car Inspection',
            'Timing Belt Replacement',
            'Air Filter Replacement',
            'Starter Replacement',
            'Spark Plugs Replacement',
            'Battery Replacement',
            'Alternator Replacement',
        ];
       
        foreach ($tp2 as $type) {
            CarServiceType::create([
                'major_service_type_id' => 2,
                'serviceType' => $type
            ]);
        }
        $brakefaults=[
            'ABS Speed Sensor Replacement',
            'Wheel Speed Sensor Replacement',
            'Brake Drum Replacement',
            'Brake Caliper Replacement',
            'Brake Hose Replacement',
            'Brake Master Cylinder Replacement',
            'Brake Pads Replacement',
            'Brake Rotor/Disc Replacement',
            'Brake Shoes (Rear) Replacement',
            'Emergency / Parking Brake Shoe Replacement',
            'Brake Wheel Cylinder Replacement',
            'Emergency / Parking Brake Cable Replacement',
            'Brake System Flush',
            'Vacuum Brake Booster Check Valve Replacement',
            'Vacuum Pump Replacement',
            'Wheel Hub Assembly Replacement',
            'Brake Vacuum Pump Replacement',
            'Emergency Brake Control Replacement',
            'Parking Brake Release Cable Replacement',
            'Anti-Lock Control Relay Replacement',
            'Anti-Lock Fuses Or Relay Replacement',
        ];
        foreach ($brakefaults as $type) {
            CarServiceType::create([
                'major_service_type_id' => 4,
                'serviceType' => $type
            ]);
        }
        $engings=[
            'Fuel Filter Replacement',
            'Fuel Injector Replacement',
            'Fuel Pressure Regulator Replacement',
            'Fuel Pump Replacement',
            'Oxygen Sensor Replacement',
            'Gas Cap Replacement',
            'Fuel Filler Neck Replacement',
            'Fuel Tank Pressure Sensor Replacement',
            'Fuel Gauge Sender Replacement',
            'Fuel Filler Cap Replacement',
            'Carburetor Replacement',
            'Fuel Injector O Rings Replacement',
            'Fuel Pressure Sensor Replacement',
            'Injector Control Pressure Sensor Replacement',
            'Fuel Pressure Damper Replacement',
            'Alternator Replacement',
            'Crankshaft Harmonic Balancer Replacement',
            'Exhaust Gas Recirculation/EGR Valve Replacement',
            'Engine Mount Replacement',
            'Exhaust Manifold Gasket Replacement',
            'Exhaust Manifold Replacement',
            'Idle Control Valve Replacement',
            'Intake Manifold Gaskets Replacement',
            'Oil Pan Gasket Replacement',
            'Positive Crankcase Ventilation (PCV) Valve Replacement',
            'Cooling/Radiator Fan Motor Replacement',
            'Radiator Replacement',
            'Serpentine/Drive Belt Replacement',
            'Starter Replacement',
            'Thermostat Replacement',
            'Throttle Body Replacement',
            'Valve Cover Gasket Replacement',
            'Water Pump Replacement',
            'Distributor Rotor and Cap Replacement',
            'Exhaust Gas Recirculation (EGR) Tube Replacement',
            'Idler Pulley Replacement',
            'PCV Valve Hose Replacement',
            'Oil Cooler Hose (Automatic Transmission) Replacement',
            'Cooling System Flush',
            'Radiator Flush',
            'Tune-up',
            'Pressure Test Radiator Cap',
            'Throttle Controller Replacement',
            'Camshaft Seal Replacement',
            'Front Crankshaft Seal Replacement',
            'Oil Pan Replacement',
            'Oil Filter Housing Gasket Replacement',
            'Oil Pressure Sensor Replacement',
            'Fan Clutch Replacement',
            'Manifold Absolute Pressure Sensor (MAP Sensor) Replacement',
            'Automatic Shutdown Relay Replacement',
            'Air Pump Replacement',
            'Coolant Temperature Switch (Sensor) Replacement',
            'Alternator Belt Replacement',
            'Distributor Replacement',
            'Coolant Recovery Reservoir Replacement',
            'Battery Terminal Ends Replacement',
            'Windshield Washer Reservoir Replacement',
            'Oil Temperature Sensor Replacement',
            'Coolant Reservoir Replacement',
            'Barometric Sensor Replacement',
            'Heater Hoses Replacement',
            'Timing Cover Replacement',
            'Variable Valve Timing (VVT) Solenoid Replacement',
            'Variable Valve Timing (VVT) Switch Replacement',
            'Carburetor Replacement',
            'Power Steering Belt Replacement',
            'AC Belt Replacement',
            'Oil Cooler Replacement',
            'Accelerator Cable Replacement',
            'Oil Cooler Lines Replacement',
            'Cruise Control Cable Replacement',
            'Air Bleed Housing Assembly Replacement',
            'Air Pump Check Valve Replacement',
            'Distributor O Ring Replacement',
            'Water Pump (Auxiliary) Replacement',
            'Oil Cooler Adapter Gasket Replacement',
            'Supercharger Belt Replacement',
            'Throttle Control Cable Replacement',
            'Water Pump Pulley Replacement',
            'Electronic Spark Control Replacement',
            'Vent Oil Seperator Replacement',
            'Electronic Ignition Pickup Replacement',
            'Points & Condenser Replacement',
            'Intake Manifold Runner Control Replacement',
            'Oil Pump O Ring Replacement',
            'Heater Bypass Tube Replacement',
            'Timing Cover Gasket',
            'Thermostat Housing Replacement',
            'Engine Variable Valve Timing (VVT) Oil Control Valve Replacement',
            'Engine Variable Valve Timing (VVT) Adjuster Magnet Replacement',
            'Engine Variable Valve Timing (VVT) Eccentric Shaft Sensor Replacement',
            'Valve Cover Replacement',
            'Oil Separator Replacement',
            'Boost Pressure Sensor Replacement',
            'Oil Filter Housing Replacement',
            'Breather Hose Replacement',
            'EGR Vacuum Solenoid Replacement',
            'Eccentric Shaft Sensor Replacement',
            'Bypass Hose Replacement',
            'EGR Pressure Sensor Replacement',
            'PCV Valve Grommet Replacement',
            'Engine Oil Temperature Sensor Replacement',
            'Camshaft Adjuster Magnet Replacement',
            'Engine Camshaft Synchronizer Replacement',
            'Fuel Pressure Damper Replacement',
            'Leak Detection Pump Replacement',
            'Engine Intake Manifold Runner Control Lever Replacement',
            'Engine Intake Manifold Runner Control Sensor Replacement',
            'Engine Intake Manifold Runner Vacuum Actuator Replacement',
            'Engine Intake Manifold Runner Vacuum Control Motor Replacement',
            'Engine Oil Temperature Switch Replacement',
        ];

        foreach ($engings as $type) {
            CarServiceType::create([
                'major_service_type_id' => 5,
                'serviceType' => $type
            ]);
        }
        $clusthchs=[
            'Axle / CV Shaft Assembly Replacement',
            'Clutch Slave Cylinder Replacement',
            'Clutch Master Cylinder Replacement',
            'Clutch Fluid Replacement',
            'Transfer Case Fluid Replacement',
            'Transmission Fluid Service',
            'Clutch Switch Replacement',
            'Transmission Position Sensor (Switch) Replacement',
            'Differential Gasket Replacement',
            'Axle Shaft Seal Replacement',
            'Speedometer Cable Replacement',
            'Center Support Bearing Replacement',
            'Speed Sensor Replacement',
            'Transmission Speed Sensor Replacement',
            'Clutch Cable Replacement',
            'Shifter Interlock Solenoid Replacement',
            'Shift Selector Cable Replacement',
            'Clutch Safety Switch Replacement',
            'Flexible Clutch Hose Replacement',
            'Differential Output Seal Replacement',
            'Speedometer Cable and Housing Replacement',
            'Transmission Oil Pressure Switch Replacement',
            'Shift Interlock Solenoid Replacement',
            'Manual Transmission Shift Cable Replacement',
            'Shift Interlock Cable Replacement',
            'Manual Transmission Shift Lever Replacement',
            'Automatic Transmission Shift Lever Assembly Replacement',
        ];
        foreach ($clusthchs as $type) {
            CarServiceType::create([
                'major_service_type_id' => 6,
                'serviceType' => $type
            ]);
        } 
        
        $heatings=[
            'AC Compressor Replacement',
            'AC Condenser Fan Replacement',
            'AC Condenser Replacement',
            'AC Low Pressure Hose Replacement',
            'Heater Blower Motor Replacement',
            'Heater Blower Motor Resistor Replacement',
            'Heater Control Valve Replacement',
            'AC Recharge',
            'AC is not working (Inspection)',
            'AC Receiver Dryer Replacement',
            'AC Accumulator Replacement',
            'AC High Pressure Hose Replacement',
            'Condenser Fan Relay Replacement',
            'Expansion Valve (Orifice Tube) Replacement',
            'Blower Motor Switch Replacement',
            'AC Compressor Relay Replacement',
            'AC High Pressure Switch Replacement',
            'AC Pressure Switch Replacement',
            'Blower Motor Relay Replacement',
            'AC Control Switch Replacement',
            'AC Clutch Cycling Switch Replacement',
            'AC Low Pressure Switch Replacement',
            'AC Refrigerant Suction Hose Replacement',
            'Auxiliary Fan Control Unit Replacement',
            'AC Refrigerant Discharge Hose Replacement',
            'AC Refrigerant Liquid Hose Replacement',
            'AC Suction Line Hose Assembly Replacement',
        ];
        foreach ($heatings as $type) {
            CarServiceType::create([
                'major_service_type_id' => 7,
                'serviceType' => $type
            ]);
        } 
        
        $suspensions=[
            'Axle / CV Shaft Assembly Replacement',
            'Differential / Gear Oil Replacement',
            'Suspension Springs Replacement',
            'Universal Joint (U-joint) Replacement',
            'Strut Assembly Replacement',
            'Wheel Bearings Replacement',
            'Ball Joint Front Replacement',
            'Control Arm Assembly Replacement',
            'Ball Joint Rear Replacement',
            'Power Steering Pump Replacement',
            'Power Steering Fluid Reservoir Replacement',
            'Shock Absorber Replacement',
            'Tie Rod End Replacement',
            'Power Steering Pressure Hose Replacement',
            'Lubricate U-Joints',
            'Lubricate Ball Joints',
            'Lubricate Suspension',
            'Lubricate Driveshaft',
            'Lubricate Steering and Suspension',
            'Tighten Wheel Lug Nuts',
            'Power Steering Fluid Service',
            'Steering Rack/Gearbox Replacement',
            'Air Shocks Replacement',
            'Center (Drag) Link Replacement',
            'Stabilizer Bar Bushings Replacement',
            'Stabilizer Bar Links Replacement',
            'Pitman Arm Replacement',
            'Wheel Stud Replacement',
            'Steering Damper Replacement',
            'Air Suspension Air Compressor Replacement',
            'Air Spring Bag Replacement',
            'Air Springs Replacement',
            'Drag Link Replacement',
            'Differential Fluid Service Replacement',
            'Power Steering Pump Pulley Replacement',
            'Track Bar Replacement',
            'Lateral Link Replacement',
            'Suspension Air Bag Replacement',
            'Steering Stabilizer Stop Replacement',
            'Power Steering Pressure Switch Replacement',
            'Power Steering Input Shaft Seal Replacement',
            'Power Steering Return Hose Replacement',
            'Suspension Strut Mount Replacement',
            'Sway Bar Replacement',
            'Idler Arm Replacement',
            'Thrust Arm Replacement',
        ];

        foreach ($suspensions as $type) {
            CarServiceType::create([
                'major_service_type_id' => 8,
                'serviceType' => $type
            ]);
        }        
        $exterirs=[
            'Windshield Wiper Blade Replacement',
            'Front Windshield Wiper Blade Replacement',
            'Rear Window Wiper Blade Replacement',
            'Rear Windshield Wiper Blade Replacement',
            'Windshield Wiper Motor Replacement',
            'Windshield Wiper Switch Replacement',
            'Windshield Washer Pump Replacement',
            'Clean and Repack Wheel Bearing',
            'Washer fluid does not spray onto windshield (Inspection)',
            'Window Motor / Regulator Assembly Replacement',
            'Wiper Gearbox Replacement',
            'Windshield Wiper/Washer System Inspection',
            'Clean Windshield Washer Tubes and Jets (Inspection)',
            'Adjust Windshield Washer Jets',
            'Windshield Wiper Arm Replacement',
            'Windshield Wiper Linkage Replacement',
            'Windshield Wiper Refill Replacement',
            'Power Window Switch Replacement',
            'Window Motor / Regulator Assembly Replacement',
            'Door Mirror Replacement',
            'Door Lock Actuator Replacement',
            'Door Lock Relay Replacement',
            'Door Lock Switch Replacement',
            'Exterior Door Handle Replacement',
            'Interior Door Handle Replacement',
            'Door Latch Replacement',
            'Hood Latch Replacement',
            'Lubricate Doors',
            'Lubricate Hood Hinge',
            'Lubricate Trunk',
            'Trunk Lock Actuator Replacement',
            'Trunk Latch Adjustment',
            'Hood Lift Support Shocks Replacement',
            'Trunk Lift Support Shocks Replacement',
            'Trunk Latch Replacement',
            'Trunk Latch Release Cable Replacement',
            'Hood Release Cable Replacement',
            'Tailgate Handle Replacement',
            'Door Latch Cable Replacement',
            'Hood Release Handle Replacement',
            'Liftgate Latch Replacement',
            'Headlight Lens Assembly Replacement',
            'Deck Lid Release Cable Replacement',
            'Liftgate Lock Assembly Replacement',
        ];

        foreach ($exterirs as $type) {
            CarServiceType::create([
                'major_service_type_id' => 9,
                'serviceType' => $type
            ]);
        }

        $electricals=[
            'ABS Speed Sensor Replacement',
            'Wheel Speed Sensor Replacement',
            'Crankshaft Position Sensor Replacement',
            'Camshaft Position Sensor Replacement',
            'Speedometer Sensor Replacement',
            'Mass Airflow Sensor Replacement',
            'Oxygen Sensor Replacement',
            'Throttle Position Sensor Replacement',
            'Fuel Tank Pressure Sensor Replacement',
            'Yaw Rate Sensor Replacement',
            'Coolant Level Sensor Replacement',
            'Manifold Temperature Sensor Replacement',
            'Oil Temperature Sensor Replacement',
            'Throttle/Accelerator Pedal Position Sensor Replacement',
            'Air Charge Temperature Sensor Replacement',
            'Air Cleaner Temperature Sensor Replacement',
            'Top Dead Center (TDC) Sensor Replacement',
            'Low Water Sensor Replacement',
            'Intermittent Wiper Relay Replacement',
            'Instrument Voltage Regulator Replacement',
            'Throttle Body Position Sensor Replacement',
            'Engine Variable Valve Timing (VVT) Adjuster Magnet Replacement',
            'Engine Variable Valve Timing (VVT) Eccentric Shaft Sensor Replacement',
            'Boost Pressure Sensor Replacement',
            'Eccentric Shaft Sensor Replacement',
            'EGR Pressure Sensor Replacement',
            'Engine Oil Temperature Sensor Replacement',
            'Engine Intake Manifold Runner Control Sensor Replacement',
            'Brake Light Switch Replacement',
            'Door Lock Switch Replacement',
            'Headlight Switch Replacement',
            'Ignition Switch Replacement',
            'Power Seat Switch Replacement',
            'Power Window Switch Replacement',
            'Turn Signal Switch Replacement',
            'Clutch Switch Replacement',
            'Backup Light Switch Replacement',
            'Neutral Safety Switch Replacement',
            'Blower Motor Switch Replacement',
            'Combination Switch Assembly Replacement',
            'Clutch Safety Switch Replacement',
            'AC Control Switch Replacement',
            'Engine Oil Temperature Switch Replacement',
            'Brake Light Bulb Replacement',
            'Brake Light Switch Replacement',
            'Fog/Driving Light Bulb Replacement',
            'Headlight Bulb Replacement',
            'Headlight Switch Replacement',
            'Tail Lamp Bulb Replacement',
            'Turn Signal Bulb Replacement',
            'Turn Signal Switch Replacement',
            'Reverse Light Bulb Replacement',
            'Reset Indicator Lights',
            'License Plate Light Replacement',
            'Dome Light Bulb Replacement',
            'Console Light Bulb Replacement',
            'Courtesy Light Bulb Replacement',
            'Fog Light Relay Replacement',
            'Trunk Light Bulb Replacement',
            'Hazard / Turn Signal Flasher Replacement',
            'Combination Switch Assembly Replacement',
            'Tail Light Lens Replacement',
            'Headlight Closure Relay Replacement',
            'Cornering Light Replacement',
            'Daytime Running Lights Replacement',
            'Fog Light Lens Replacement',
            'Map Light Bulb Replacement',
            'Center High Mount Stop Light Replacement',
            'Center High Mount Stop Light Bulb Replacement',
            'Ignition Coil Replacement',
            'Ignition Switch Replacement',
            'Ignition Cable (Spark plug wires) Replacement',
            'Spark Plugs Replacement',
            'Distributor Rotor and Cap Replacement',
            'Ignition Relay Replacement',
            'Ballast Resistor Replacement',
            'Electronic Ignition Pickup Replacement',
            'Ignition Ignitor Replacement',
            'Battery Cable Replacement',
            'Battery Replacement',
            'Service Battery/cables',
            'Auxiliary Battery Replacement',
        ];
        foreach ($electricals as $type) {
            CarServiceType::create([
                'major_service_type_id' => 10,
                'serviceType' => $type
            ]);
        }
      
    }
}
 